language: php
php:
- 5.5
- 5.6
before_script: make install-dependencies-dev
script:
- make tests
- make code-sniffer
after_script:
  - php vendor/bin/coveralls -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#honeybee"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
